branches:
    - main
    - master

plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - [
          "@semantic-release/changelog",
          {
              "changelogFile": "CHANGELOG.md",
              "changelogTitle": "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n",
          },
      ]
    - [
          "@semantic-release/git",
          { "assets": ["CHANGELOG.md", "composer.json"], "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}" },
      ]
    - ["@semantic-release/github", { "successComment": false, "failComment": false, "releasedLabels": false }]

preset: "conventionalcommits"

parserOpts:
    noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
        - "BREAKING"

writerOpts:
    groupBy: "type"
    commitGroupsSort: "title"
    commitsSort: "header"

releaseRules:
    - type: "feat"
      release: "minor"
    - type: "fix"
      release: "patch"
    - type: "perf"
      release: "patch"
    - type: "revert"
      release: "patch"
    - type: "docs"
      release: false
    - type: "style"
      release: false
    - type: "chore"
      release: false
    - type: "refactor"
      release: "patch"
    - type: "test"
      release: false
    - type: "build"
      release: false
    - type: "ci"
      release: false
    - scope: "no-release"
      release: false
